#!/usr/bin/env bash

export DOTFILES_VERSION=2.0

DOTFILES_OS_ROOT=$DOTFILES_ROOT/os/common

# Add $DOTFILES_OS_ROOT/bin to $PATH
if [[ $PATH != *$DOTFILES_OS_ROOT/bin* ]]; then
    export PATH=$PATH:$DOTFILES_OS_ROOT/bin
fi

# ---- BEGIN HISTORY SYNC IN ALL TERMINAL ----
shopt -s histappend              # append new history items to .bash_history
export HISTCONTROL=ignorespace:ignoredups:erasedups   # leading space hides commands from history
export HISTFILESIZE=10000        # increase history file size (default is 500)
export HISTSIZE=${HISTFILESIZE}  # increase history size (default is 500)
export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"   # mem/file sync
# ---- END HISTORY SYNC IN ALL TERMINAL ----

# ---- BEGIN WINDOW ----
# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
# ---- END WINDOW ----

# ---- BEGIN VARIABLES ----
if [ -e $DOTFILES_OS_ROOT/variables ]; then
    source $DOTFILES_OS_ROOT/variables
fi
# ---- END VARIABLES ----

# ---- BEGIN PYTHON ----
export PYTHONIOENCODING='utf8'
# ---- END PYTHON ----

# ---- START BASH COMPLETION ----
if [ -d $DOTFILES_OS_ROOT/bash_completion.d ]; then
    for f in $DOTFILES_OS_ROOT/bash_completion.d/*; do
    source $f
    done
fi
# ---- END BASH COMPLETION ----

# ---- BEGIN ALIASES ----
if [ -d $DOTFILES_OS_ROOT/bash_aliases.d ]; then
    for f in $DOTFILES_OS_ROOT/bash_aliases.d/*; do
    source $f
    done
fi
# ---- END ALIASES ----

# ---- BEGIN FUNCTIONS ----
if [ -d $DOTFILES_OS_ROOT/bash_functions.d ]; then
    for f in $DOTFILES_OS_ROOT/bash_functions.d/*; do
        source $f
    done
fi
# ---- END FUNCTIONS ----

# ---- BEGIN BINDINGS ----
if [[ $- =~ .*i.* ]]; then
    bind '"\e[A":history-search-backward'
    bind '"\e[B":history-search-forward'
    bind '"\e[1;5C":forward-word'
    bind '"\e[1;5D":backward-word'
fi
# ---- END BINDINGS ----

# ---- BEGIN PROMPT ----
source $DOTFILES_OS_ROOT/bash_prompt
# ---- END PROMPT ----

# ---- BEGIN CHOOSE OS ----
if [[ $(uname -a) = *[Ss]ynology* ]]; then
    source $DOTFILES_ROOT/os/nas/bashrc
elif [[ $(uname -a) = *[Ll]inux* ]]; then
    source $DOTFILES_ROOT/os/linux/bashrc
elif [[ $(uname -a) = *[Dd]arwin* ]]; then
    source $DOTFILES_ROOT/os/mac/bashrc
fi
# ---- END CHOOSE OS ----