#!/usr/bin/env bash

function install() {
    local DOTFILES_OS_ROOT=$DOTFILES_ROOT/os/common

    echo -e "${BOLD}${GREEN}[INSTALLING]${RESET} dotfiles lines to \$HOME/.bashrc"
    echo "
    #Added by DOTFILES #DOTFILES
    export DOTFILES_ROOT=$DOTFILES_ROOT #DOTFILES
    source $DOTFILES_OS_ROOT/bashrc #DOTFILES" >> $HOME/.bashrc
    
    echo -e "${BOLD}${GREEN}[INSTALLING]${RESET} dotfiles lines to \$HOME/.bash_profile"
    echo "
    #Added by DOTFILES #DOTFILES
    if [ -f ~/.bashrc ]; then #DOTFILES
    source ~/.bashrc #DOTFILES
    fi #DOTFILES" >> $HOME/.bash_profile

    if [[ ! -e $HOME/.gitconfig ]]; then
        echo -e "${BOLD}${GREEN}[LINKING]${RESET} \$HOME/.gitconfig -> \$DOTFILES_OS_ROOT/home/.gitconfig"
        ln -fs $DOTFILES_OS_ROOT/home/.gitconfig $HOME/.gitconfig
    fi

    if [[ ! -e $HOME/.ssh/config ]]; then
        echo -e "${BOLD}${GREEN}[LINKING]${RESET} \$HOME/.ssh/config -> \$DOTFILES_OS_ROOT/home/.ssh/config"
        ln -fs $DOTFILES_OS_ROOT/home/.ssh/config $HOME/.ssh/config
    fi
}

install