#!/usr/bin/env bash

function remove_common () {
    local DOTFILES_OS_ROOT=$DOTFILES_ROOT/os/common
    
    echo -e "${BOLD}${RED}[REMOVING]${RESET} dotfiles added lines from \$HOME/.bashrc"
    sed -i'.dotfiles.bak' -e '/.*#DOTFILES$/d' -e '/^\s*$/d' $HOME/.bashrc
    
    echo -e "${BOLD}${RED}[REMOVING]${RESET} dotfiles added lines from \$HOME/.bash_profile"
    sed -i'.dotfiles.bak' -e '/.*#DOTFILES$/d' -e '/^\s*$/d' $HOME/.bash_profile

    echo -e "${BOLD}${RED}[REMOVING]${RESET} symlink to \$HOME/.gitconfig"
    if [[ -h $HOME/.gitconfig ]]; then
        rm $HOME/.gitconfig
    fi

    echo -e "${BOLD}${RED}[REMOVING]${RESET} symlink to \$HOME/.ssh/config"
    if [[ -h $HOME/.ssh/config ]]; then
        rm $HOME/.ssh/config
    fi
}

remove_common