#!/usr/bin/env bash

_EDITOR="nano"

export EDITOR="$_EDITOR"
export GIT_EDITOR="$_EDITOR"
export CVSEDITOR="$_EDITOR"
export VISUAL="$_EDITOR"

LS_CUSTOM_FLAGS="-Fh"

# ---- BEGIN COLORS ----
### Prompt Colors
# Modified version of @gf3’s Sexy Bash Prompt
# (https://github.com/gf3/dotfiles)
# if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
#     export TERM=gnome-256color
# elif infocmp xterm-256color >/dev/null 2>&1; then
#     export TERM=xterm-256color
# fi

export BLACK="\[\033[30m\]"
export RED="\[\033[31m\]"
export GREEN="\[\033[32m\]"
export YELLOW="\[\033[33m\]"
export BLUE="\[\033[34m\]"
export PURPLE="\[\033[35m\]"
export CYAN="\[\033[36m\]"
export WHITE="\[\033[37m\]"
export BOLD="\[\033[1m\]"
export RESET="\[\033[0m\]"

# ---- END COLORS ----