#! /usr/bin/env zsh

host-info() {
    echo "Host package installation"
    echo ${HOST_PACKAGES[@]}

}

HOST_PACKAGES=(
    ark
    base
    base-devel
    btrfs-progs
    cups
    dkms
    dolphin
    dosfstools
    efibootmgr
    egl-wayland
    fzf
    git
    gst-plugin-pipewire
    htop
    intel-ucode
    iwd
    kate
    konsole
    krdp
    less
    lib32-nvidia-utils
    libpulse
    linux
    linux-firmware
    linux-headers
    man-db
    man-pages
    nano
    network-manager-applet
    networkmanager
    nvidia-dkms
    partitionmanager
    pipewire
    pipewire-alsa
    pipewire-jack
    pipewire-pulse
    plasma-meta
    plasma-workspace
    plymouth
    smartmontools
    sof-firmware
    spectacle
    stow
    vim
    wget
    wireless_tools
    wireplumber
    xdg-utils
    xorg-xeyes
    xorg-xinit
    zram-generator
    zsh
)

host-pre-install() {
    log-info "HOST($INSTALATION_HOST) - Executing pre-install hook"
}

host-install() {
    log-info "HOST($INSTALLATION_HOST) - Executing install hook"

    if [ "$DRY_RUN" = false ]; then
        sudo pacman -Sy ${PACMAN_FLAGS[@]} ${HOST_PACKAGES[@]}
    fi

    # Files in root should be installed for security reasons
    find hosts/$INSTALLATION_HOST -mindepth 2 -type f -printf "%P\n" \
    | xargs -I{} sudo install -C -D -m544 -oroot hosts/$INSTALLATION_HOST/{} /{}
}

host-post-install() {
    log-info "HOST($INSTALATION_HOST) - Executing pos-install hook"

    sudo systemctl enable --now bluetooth.service 
    sudo systemctl enable --now cups.socket
    sudo systemctl enable --now avahi-daemon.socket
}