#!/usr/bin/env sh

nas() {
    echo "Starting remote ssh port redirect from nas.crespo.com.br:1234 to localhost:22"
    until `ssh -p 3456 fernando@nas.crespo.com.br -R 1234:localhost:22 -N`; do
        echo "Restarting remote ssh port redirect from nas.crespo.com.br:1234 to localhost:22"
        sleep 1
    done
}

reverse-ssh-connection-nas() {
    echo "Starting remote ssh port redirect from nas:1234 to localhost:22"
    until `ssh -p 3456 root@nas.crespo.com.br -R 1234:localhost:22 -N`; do
        echo "Restarting remote ssh port redirect from nas:1234 to localhost:22"
        sleep 1
    done
}

ssh-nas() {
    ping -c 1 -t 1 192.168.1.2 > /dev/null
    if [ $? -eq 0 ]; then
        ssh -p 3456 fernando@192.168.1.2
    else
        ssh -p 3456 fernando@nas.crespo.com.br
    fi 
}

ssh-pi() {
    ping -c 1 -t 1 192.168.1.3 > /dev/null
    if [ $? -eq 0 ]; then
        ssh pi@192.168.1.3
    else
        ssh pi@192.168.1.3 -J fernando@nas.crespo.com.br:3456
    fi 
}

ssh-renegade() {
    ping -c 1 -t 1 192.168.1.11 > /dev/null
    if [ $? -eq 0 ]; then
        ssh fernando@192.168.1.11
    else
        ssh fernando@192.168.1.11 -J fernando@nas.crespo.com.br:3456
    fi 
}