#!/usr/bin/env zsh

if [ "$(which brew)" = "" ]; then 
	echo "Installing homebrew"
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
	echo "Homebrew already installed"
fi

if [ ! -d "$HOME/.oh-my-zsh" ]; then 
	echo "Installing oh-my-zsh"
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
else
	echo "oh-my-zsh already installed"
fi

if [ "$(which asdf)" = "" ]; then 
	echo "Installing asdf"
	git clone https://github.com/asdf-vm/asdf.git ~/.asdf
	source $HOME/.asdf/asdf.sh
	plugins=(java maven python ruby nodejs)
	for plugin in $plugins; do
		asdf plugin add $plugin
	done
else
	echo "asdf already installed"
fi