#!/usr/bin/env sh

pgrep() {
    command pgrep -fla $@ | grep --color -E "^[0-9]+"
}

nas() {
    echo "Starting remote ssh port redirect from nas.crespo.com.br:1234 to localhost:22"
    until `ssh -p 3456 fernando@nas.crespo.com.br -R 1234:localhost:22 -N`; do
        echo "Restarting remote ssh port redirect from nas.crespo.com.br:1234 to localhost:22"
        sleep 1
    done
}

psc() {
    cmd='ps axo %cpu,pid,ppid,user,command'
    if [ "$1" = "" ]; then
        echo $cmd
        $cmd;
    else
        echo $cmd
        $cmd | grep "$1" | grep -v "grep $1" | grep -v "bin/psc" | grep -v '$cmd';
    fi;
}

count() {
    if [ $1 = "" ]; then
        ls -1 | wc -l | sed "s/ //g"
    else
        while getopts ":a" arg; do
            case "$arg" in
                a) ls -A1 | wc -l | sed "s/ //g";; 
                \?) echo -e "Usage:\n\tcount   \tCount files in a folder (except hidden)\n\tcount -a\tCount files in a folder including hidden";;
            esac
            shift $((OPTIND-1))
        done
    fi
}

to_mp4() {
    FFMPEG=`which ffmpeg`
    file=$1
    $FFMPEG -i "$file" "${file%.*}.mp4"
}

to_mp3() {
    FFMPEG=`which ffmpeg`
    file=$1
    $FFMPEG -i "$file" "${file%.*}.mp3"
}

git-status-recursive() {
    find . -name .git -execdir bash -c 'echo -en "\033[1;31m"repo: "\033[1;34m"; basename "`git rev-parse --show-toplevel`"; git status -s' \; 
}


reverse-ssh-connection-nas() {
    echo "Starting remote ssh port redirect from nas:1234 to localhost:22"
    until `ssh -p 3456 root@nas.crespo.com.br -R 1234:localhost:22 -N`; do
        echo "Restarting remote ssh port redirect from nas:1234 to localhost:22"
        sleep 1
    done
}

java-asdf-link() {
    echo $fg_bold[yellow]To create links on $macOS_java_dir this script needs Super User powers.$reset_color
    macOS_java_dir=/Library/Java/JavaVirtualMachines
    asdf_java_dir=$ASDF_DIR/installs/java

    if [ -d $asdf_java_dir ]; then
        installs=( $(find $asdf_java_dir -type d -depth 1 -print) )
        for install in ${installs[*]}; do
            found=$(find $install -name Home -print)
            if [ ! -z $found ]; then
                destination=$(dirname $(dirname $found))
                source=${destination##*/}
                sudo ln -sf "$destination" "$macOS_java_dir/$source"
            fi
        done
    fi
}

rename-from-exif() {
    exiftool '-filename<DateTimeOriginal' -d %Y-%m-%d-%H-%M-%S%%-c.%%le $1
}

rename-multiple-from-exif() {
    for file in $@; do
        rename-from-exif $file
    done
}

ssh-nas() {
    ping -c 1 -t 1 192.168.1.2 > /dev/null
    if [ $? -eq 0 ]; then
        ssh -p 3456 fernando@192.168.1.2
    else
        ssh -p 3456 fernando@nas.crespo.com.br
    fi 
}

ssh-pi() {
    ping -c 1 -t 1 192.168.1.3 > /dev/null
    if [ $? -eq 0 ]; then
        ssh pi@192.168.1.3
    else
        ssh pi@192.168.1.3 -J fernando@nas.crespo.com.br:3456
    fi 
}

ssh-renegade() {
    ping -c 1 -t 1 192.168.1.11 > /dev/null
    if [ $? -eq 0 ]; then
        ssh fernando@192.168.1.11
    else
        ssh fernando@192.168.1.11 -J fernando@nas.crespo.com.br:3456
    fi 
}