#!/usr/bin/env bash

export DOTFILES_ROOT=$(pwd)

if [[ -e $DOTFILES_ROOT/os/common/install ]]; then
    bash $DOTFILES_ROOT/os/common/install
fi

if [[ $(uname -a) = *[Ss]ynology* ]]; then
    export DOTFILES_OS="nas"
elif [[ $(uname -a) = *[Ll]inux* ]]; then
    export DOTFILES_OS="linux"
elif [[ $(uname -a) = *[Dd]arwin* ]]; then
    export DOTFILES_OS="mac"
fi

if [[ -e $DOTFILES_ROOT/os/$DOTFILES_OS/install ]]; then
    bash $DOTFILES_ROOT/os/$DOTFILES_OS/install
fi
