#!/usr/bin/env bash

DOTFILES_ROOT=$(pwd)

sed -i'.dotfiles.bak' -e '/.*#DOTFILES$/d' -e '/^\s*$/d' $HOME/.bashrc
sed -i'.dotfiles.bak' -e '/.*#DOTFILES$/d' -e '/^\s*$/d' $HOME/.bash_profile

if [[ -e $DOTFILES_ROOT/os/common/remove ]]; then
    bash $DOTFILES_ROOT/os/common/remove
fi

if [[ $(uname -a) = *[Ss]ynology* ]]; then
    export DOTFILES_OS="nas"
elif [[ $(uname -a) = *[Ll]inux* ]]; then
    export DOTFILES_OS="linux"
elif [[ $(uname -a) = *[Dd]arwin* ]]; then
    export DOTFILES_OS="mac"
fi

if [[ -e $DOTFILES_ROOT/os/$DOTFILES_OS/remove ]]; then
    bash $DOTFILES_ROOT/os/$DOTFILES_OS/remove
fi