#!/usr/bin/env sh

debug() {
	if [ ! -z "$DOTFILES_DEBUG" ]; then
		echo $@
	fi
}

dotfiles-update() {
	env DOTFILES_DIR=$DOTFILES_DIR sh $DOTFILES_DIR/tools/upgrade.sh
}

alias update-dotfiles=dotfiles-update

ensure_zsh() {
	if [ -z $(command -v zsh) ]; then
		echo "Installing zsh"
		case $(uname -s) in
			Linux)
				sudo apt-get update && sudo apt-get install -y zsh
				;;
			Darwin)
				ensure_homebrew
				brew install zsh
				;;
		esac
	fi
}

ensure_homebrew() {
	if [ -z $(command -v brew) ]; then
		echo "Installing brew"
		case $(uname -s) in
			Darwin)
				/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
				;;
		esac
	fi
}