#!/usr/bin/env sh

debug() {
	if [ ! -z "$DOTFILES_DEBUG" ]; then
		echo $@
	fi
}

upgrade_dotfiles() {
	env DOTFILES_DIR=$DOTFILES_DIR sh $DOTFILES_DIR/tools/upgrade.sh
}

ensure_homebrew() {
	if [ -z $(command -v brew) ]; then
		echo "Installing brew"
		case $(uname -s) in
			Darwin)
				/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
				;;
		esac
	fi
}