#!/usr/bin/env zsh

debug() {
	if [ ! -z "$DOTFILES_DEBUG" ]; then
		echo $@
	fi
}

dotfiles-update() {
    (cd $DOTFILES_DIR && git pull)
	source $DOTFILES_DIR/.zshrc
}

alias update-dotfiles=dotfiles-update